### PR TITLE
[Tests/Sink] Fix test failure on macOS/Travis CI @open sesame 10/22 20:30

### PR DESCRIPTION
**Pull request by wooksong**
This PR is required to enable build-time tests NNStreamer on macOS deployed with Travis CI and mainly focuses on fixing that unittest_sink is failed.

In low performance machines such as VMs in the cloud,  there are several cases that the pipelines cannot finish their job until the pipeline is stopped.  Moreover, sometimes they even cannot keeo the given framerate so that few buffers are lost while testing. To work around this issue, this PR adds command-line options for adding jitter between start and stop pipe qnd controlling the speed of tests made of videotestsrc-based single pipeline.

Resolves a sub-item of #1608
See also: https://github.com/nnsuite/homebrew-neural-network

*Self evaluation:**
1. Build test: [*] Passed [ ]Failed [ ]Skipped
2. Run test: [*] Passed [ ]Failed [ ]Skipped

After merging this PR, only one failed test case remains.

Screenshot_20191022-004105_Samsung Internet

Signed-off-by: Wook Song <wook16.song@samsung.com>

### CODE REVIEW

File: tests/nnstreamer_sink/unittest_sink.cpp [hunk 1]
```diff
@@ -4620,15 +4688,50 @@ TEST (tensor_stream_test, tensor_decoder_property)
...
+
+  if (!g_option_context_parse (optionctx, &argc, &argv, &error)) {
+    g_print ("option parsing failed: %s\n", error->message);
+
+    return 1;
+  }
+
+  jitter = 0UL;
+  if ((jitter_cmd_arg != NULL) &&
+      !g_ascii_string_to_unsigned (jitter_cmd_arg, 10, 0UL,
```
Comment (myungjoo) [inline tests/nnstreamer_sink/unittest_sink.cpp]:
```
[   52s] ../tests/nnstreamer_sink/unittest_sink.cpp:4723:56: error: 'g_ascii_string_to_unsigned' was not declared in this scope
[   52s]            (G_MAXULONG / MSEC_PER_USEC), &jiiter64, NULL)) {
[   52s]                                                         ^
[   52s] ../tests/nnstreamer_sink/unittest_sink.cpp:4731:35: error: 'g_ascii_string_to_unsigned' was not declared in this scope
[   52s]            G_MAXULONG, &fps64, NULL)) {
```

Comment (wooksong) [reply tests/nnstreamer_sink/unittest_sink.cpp]: @myungjoo ```g_ascii_string_to_unsigned`` is available after 2.54. I changed it to ```g_ascii_strtoull```.

**Comment by wooksong** [comment]
V2: ```g_ascii_string_to_unsigned``` is replaced with ```g_ascii_strtoull```.

**Comment by jaeyun-jung** [comment]
Error occurs in meson script
```
Meson encountered an error in file tests/meson.build, line 101, column 68:
Expecting eof got eol_cont.
tensor_filter_ext_enabled = get_option('enable-tensorflow-lite') or \
```

Now updated meson with 0.50, let's see the app-test result.

**Comment by wooksong** [comment]
#### V4
- Work-around meson's bug about line continuation policy

The specification documentation of meson states as follows:
> Function and method calls' argument lists can be split over multiple lines. Meson will autodetect this case and do the right thing. In other cases you can get multi-line statements by ending the line with a \\.

However, until meson v0.49, meson has not worked according to the specification statement. This is a meson-side bug. The last commit, [Tests/Meson] Add missing line continuation, is to work around this issue. 

Related to https://github.com/mesonbuild/meson/issues/4720
See also: https://github.com/mesonbuild/meson/commit/90c9b868b20b11bb089fc5e0c634d5ed76fea0cb

**Comment by jaeyun-jung** [comment]
> #### V4
> * Work-around meson's bug about line continuation policy
> 
> The specification documentation of meson states as follows:
> 
> > Function and method calls' argument lists can be split over multiple lines. Meson will autodetect this case and do the right thing. In other cases you can get multi-line statements by ending the line with a \.
> 
> However, until meson v0.49, meson has not worked according to the specification statement. This is a meson-side bug. The last commit, [Tests/Meson] Add missing line continuation, is to work around this issue.
> 
> Related to [mesonbuild/meson#4720](https://github.com/mesonbuild/meson/issues/4720)
> See also: [mesonbuild/meson@90c9b86](https://github.com/mesonbuild/meson/commit/90c9b868b20b11bb089fc5e0c634d5ed76fea0cb)

@wooksong how about updating the meson version? (>=0.50)

**Comment by wooksong** [comment]
> > #### V4
> > 
> > * Work-around meson's bug about line continuation policy
> > 
> > The specification documentation of meson states as follows:
> > > Function and method calls' argument lists can be split over multiple lines. Meson will autodetect this case and do the right thing. In other cases you can get multi-line statements by ending the line with a .
> > 
> > 
> > However, until meson v0.49, meson has not worked according to the specification statement. This is a meson-side bug. The last commit, [Tests/Meson] Add missing line continuation, is to work around this issue.
> > Related to [mesonbuild/meson#4720](https://github.com/mesonbuild/meson/issues/4720)
> > See also: [mesonbuild/meson@90c9b86](https://github.com/mesonbuild/meson/commit/90c9b868b20b11bb089fc5e0c634d5ed76fea0cb)
> 
> @wooksong how about updating the meson version? (>=0.50)

I totally agree with your opinion.
However, the version of meson  in Tizen is still 0.44.

**Comment by jaeyun-jung** [comment]
I found that Tizen meson ver is 0.51.
I added PR #1816  for build test in CI. Let's check the update and discuss this with that PR.

**Comment by wooksong** [comment]
#### V5
- Support meson >= 0.50 only
